//CREAMOS LO TYPES DE PROYECTOS
export const FORMULARIO_PROYECTO = 'FORMULARIO_PROYECTO';
export const OBTENER_PROYECTOS = 'OBTENER_PROYECTOS';
export const AGREGAR_PROYECTO = 'AGREGAR_PROYECTO';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const MOSTRAR_PROYECTO = 'MOSTRAR_PROYECTO';
export const ELIMINAR_PROYECTO = 'ELIMINAR_PROYECTO';

//CREAMOS LO TYPES DE TAREAS
export const TAREAS_PROYECTO = 'TAREAS_PROYECTO';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const VALIDAR_FORM = 'VALIDAR_FORM';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
